### ISSUE TITLE
How to run benchmark tests[Issue]: 

### ISSUE THREAD

**Issue by jinsong-mao** [ROCm/aotriton#30]
### Problem Description

Hi 

I can build this project by following the commands, However, there is one issue of "can't find "pyaottriton"" when I ran the benchmark tests like: benchmark_fwd.py

did I miss anything? how any other way to run the benchmark tests?

Thanks

### Operating System

ubuntu 22

### CPU

5900x

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.1.0

**Comment by xinyazhang** [comment]
`PYTHONPATH` environment variable is needed to locate `pyaotriton`. When following the build instructions in `README.md` it is `build/bindings` (relative to the root of the source).

`pyaotriton` is a python binding for unit tests, and currently there is no plan of making it a python package.

**Comment by jinsong-mao** [comment]
Thanks xinyazhang, 

is there any benchmarks to test the performance of aotriton flash attention kernel except unit test?

Thanks
Jinsong

**Comment by jinsong-mao** [comment]
Hi @xinyazhang ,

looks there still has this issue "ModuleNotFoundError: No module named 'pyaotriton'"  after setting up the PYTHONPATH environment variable. 
anything I missed on solving this issue? 

Thanks

**Comment by xinyazhang** [comment]
> is there any benchmarks to test the performance of aotriton flash attention kernel except unit test?

You can use `test/performance_forward.py` and `test/performance_backward.py` 

> anything I missed on solving this issue?

What you are looking for is a file `pyaotriton.cpython-39-x86_64-linux-gnu.so` (The `cpython-39-x86_64-linux-gnu` may be different according to your platform/python ver/etc.)

`PYTHONPATH` should point to the directory containing this shared object. If you can't find the file, set CMake option `AOTRITON_NO_PYTHON` to `OFF` and rebuild the project from source.

**Comment by jinsong-mao** [comment]
Thanks @xinyazhang ,

looks my previous build was not successful,  there is pyaotriton.cpython-39-x86_64-linux-gnu.so and PYTHONPATH was set correctly, we made progress after rebuilding the project, we can run the test of performance_forward.py.
However, the backward performance test was failed with the following message, looks the argument "causal" is one exception for bwd,  could u please take a look at it and any solutions we can make to fix it?
![image](https://github.com/ROCm/aotriton/assets/146043398/10d64607-e6ae-447f-ab45-214e76c2ced8)

**Comment by xinyazhang** [comment]
> could u please take a look at it and any solutions we can make to fix it?

Oh the `performance_backward.py` was a temporary solution and was not checked/updated frequently as other components.

You need this patch to make it work on latest main
```
diff --git a/test/performance_backward.py b/test/performance_backward.py
index 13fb13b..870824d 100644
--- a/test/performance_backward.py
+++ b/test/performance_backward.py
@@ -65,7 +65,7 @@ def bench_flash_attention(BATCH, H, N_CTX, D_HEAD, causal, mode, provider, dtype
         sm_scale = 1.3
         autotune = False
         return_encoded_softmax = False
-        fn = lambda: attention(q, k, v, causal, sm_scale, split_kernel, return_encoded_softmax, autotune)
+        fn = lambda: attention(q, k, v, None, causal, sm_scale, split_kernel, return_encoded_softmax, autotune)
         if mode == 'bwd':
             o, _, _ = fn()
             do = torch.randn_like(o)
```
The `b` argument was missing in the backward script.

**Comment by jinsong-mao** [comment]
Thanks @xinyazhang ,
It works,  


sorry to ask one question has nothing to do with this topic, are you in SC stie?  it should about 2 am right now,

**Comment by xinyazhang** [comment]
> sorry to ask one question has nothing to do with this topic, are you in SC stie? it should about 2 am right now,

No, just a sleepless night as usual.
