### ISSUE TITLE
[Issue]: build fail: ModuleNotFoundError: No module named 'triton._C.libtriton.triton'

### ISSUE THREAD

**Issue by minzhezhou** [ROCm/aotriton#35]
### Problem Description

MAX_JOBS=4 ninja install
would fail at Generating flash/gpu_kernel_image.attn_fwd/attn_fwd-Sig-F__^bf16@16_False_128_False_False_False_0__P__128_64_0__CO__warp4_stg1_wave2-Gpu-MI200.hsaco.zst
due to error:
FAILED: v2src/flash/gpu_kernel_image.attn_fwd/attn_fwd-Sig-F__^bf16@16_False_128_False_False_False_0__P__128_64_0__CO__warp4_stg1_wave2-Gpu-MI200.hsaco.zst /home/jack/code/aotriton/build/v2src/flash/gpu_kernel_image.attn_fwd/attn_fwd-Sig-F__^bf16@16_False_128_False_False_False_0__P__128_64_0__CO__warp4_stg1_wave2-Gpu-MI200.hsaco.zst 
cd /home/jack/code/aotriton/build/v2src && /home/jack/code/miniconda3/lib/python3.12/site-packages/cmake/data/bin/cmake -E env VIRTUAL_ENV=/home/jack/code/aotriton/build/venv /home/jack/code/aotriton/build/venv/bin/python /home/jack/code/aotriton/v2python/compile.py /home/jack/code/aotriton/tritonsrc/flash.py --kernel_name attn_fwd -o /home/jack/code/aotriton/build/v2src/flash/gpu_kernel_image.attn_fwd/attn_fwd-Sig-F__^bf16@16_False_128_False_False_False_0__P__128_64_0__CO__warp4_stg1_wave2-Gpu-MI200.hsaco -g 1,1,1 --num_warps 4 --num_stages 1 --waves_per_eu 2 --target MI200 --signature *bf16:16,\ *bf16:16,\ *bf16:16,\ *bf16:16,\ fp32,\ *fp32:16,\ *bf16:16,\ u64:16,\ u64:16,\ u64:16,\ 1,\ u64:16,\ u64:16,\ u64:16,\ 1,\ u64:16,\ u64:16,\ u64:16,\ 1,\ u64:16,\ u64:16,\ u64:16,\ 1,\ u64:16,\ u64:16,\ u64:16,\ 1,\ *i32:16,\ *i32:16,\ i32,\ i32,\ i32,\ i32,\ fp32,\ u64,\ u32,\ *bf16:16,\ False,\ 128,\ 128,\ 64,\ 0,\ False,\ False,\ False,\ 0 && /home/jack/code/miniconda3/bin/zstd -f /home/jack/code/aotriton/build/v2src/flash/gpu_kernel_image.attn_fwd/attn_fwd-Sig-F__^bf16@16_False_128_False_False_False_0__P__128_64_0__CO__warp4_stg1_wave2-Gpu-MI200.hsaco
TRackback:
File "/home/jack/code/aotriton/v2python/compile.py", line 12, in <module>
    import triton
    
This probably was related to triton build fail due to :
F^bf16@16_False_128_False_False_False_0P128_64_0COwarp4_stg1_wave0-Gpu-MI200.hsaco Traceback (most recent call last):  File "/home/jack/code/aotriton/v2python/compile.py", line 134, in <module>    main()  File "/home/jack/code/aotriton/v2python/compile.py", line 112, in main    config = triton.compiler.instance_descriptor(divisible_by_16=divisible_by_16, equal_to_1=equal_to_1)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'triton.compiler' has no attribute 'instance_descriptor'

### Operating System

UBUNTU 22.04

### CPU

5800XT

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.1.0

### ROCm Component

ROCm

### Steps to Reproduce

MAX_JOBS=4 ninja install would fail

**Comment by xinyazhang** [comment]
This is due to incompatibility with the Triton version you're using. Please do not update the bundled Triton submodule. It requires custom patches and only the pinned version can be used for the current release.

We are working on migrating Triton to the latest version (but still require custom patches) in order to support Navi GPUs.
